hotfix Fix migration
Fuseit/acts_as_mentionable pull request #11
Opened 2018-12-05 17:35 UTC by bazay

2018-12-06 14:14 UTC, Gikls requested changes

2018-12-06 14:14 UTC, Gikls commented on db/migrate/1_acts_as_mentionable_migration.rb
> +      t.references :mentionable, polymorphic: true
If you don't specifying index name here, it's possible to get a broken migration because of ActsAsMentionable.mentions_table may be too long, and the index name is limited length.

2018-12-06 16:11 UTC, bazay commented on db/migrate/1_acts_as_mentionable_migration.rb
> +      t.references :mentionable, polymorphic: true
Ok

2018-12-06 20:18 UTC, ux approved these changes

2018-12-06 20:18 UTC, ux commented on README.md
> +rake acts_as_mentionable:install:migrations
It seems that task name should be `acts_as_mentionable_engine:install:migrations`

2018-12-06 20:18 UTC, ux commented on db/migrate/1_acts_as_mentionable_migration.rb
> +  def self.up
I think we still can use `#change` method here, but it should be instance method, not a class method to work as expected in a AR migration.
```ruby
def change
  # ...
end
```
But this is just a suggestion.

2018-12-07 06:31 UTC, Gikls approved these changes

2018-12-07 11:55 UTC, merged