feature FINISH-647 parser for mentioner
Fuseit/acts_as_mentionable pull request #14
Opened 2019-01-15 10:05 UTC by Gikls

https://fuseuniversal.atlassian.net/browse/FINISH-647
Creating a parser. Making a settings for mentioner and mentionable - out of box.

2019-01-16 23:35 UTC, ux commented on acts_as_mentionable.gemspec
> +  spec.add_development_dependency 'faker'
Do we need `faker` at this point, as I don't see it's used?

2019-01-16 23:35 UTC, ux commented on lib/acts_as_mentionable/active_record_methods.rb
> +      def acts_as_mentionable mentionable_delimiter = '@', mentionable_field = :username
What do you think about moving changes for `acts_as_mentionable` method to a new pull request, where  `mentionable_delimiter` and `mentionable_field` will be used. Because right now it slightly confuses as it's not used and I don't know how it's gonna be used.

2019-01-16 23:35 UTC, ux commented on lib/acts_as_mentionable/active_record_methods.rb
> +      def acts_as_mentioner mention_field = :body
What do you think about explicit request for `mention_field` value in application, instead of providing the default one `body`? Because assuming that `acts_as_mentionable` is a public gem, it's unlikely that field will be named `body`. It can be `content`, `text`, `message`, `description`, `comment`, etc., anything.

2019-01-16 23:35 UTC, ux commented on lib/acts_as_mentionable/mentioner_parser.rb
> +        mentionable_klass.classify.constantize.find mentionable_id
Since we use `#classify` and `#constantize` methods then we should `add_runtime_dependency` on `activesupport` to https://github.com/Fuseit/acts_as_mentionable/blob/master/acts_as_mentionable.gemspec#L28

Also, maybe we can use something like `ActsAsMentionable:: RetrievePolymorphic` (for instance, split `RetrievePolymorphic` into 2 separate classes) in order to avoid N+1 query? _Not sure we need this for MVP though._

Or, on other hand, maybe we can take off responsibility of finding the records to the target application instead of querying them inside of the gem? Because we can get errors raised here, like `ActiveRecord::RecordNotFound` in case of deleted records or model default scopes.

2019-01-16 23:35 UTC, ux commented on lib/acts_as_mentionable/mentioner_parser.rb
> +        /\{\W\|\d+\|\w+\}/
Are we going to use a different indicator symbols except `@`? Because in this regex we are assuming that it can be any non-word character and we don't care which one is it.
Also, we can use grouping in regexp, so we don't need to parse it again above in `template.gsub(/[\{,\}]/, '').split('|')`
```suggestion
        /\{@\|(\d+)\|(\w+)\}/
```

```ruby
irb(main):025:0> 'Lorem {@|42|user} ipsum {@|256|community} dolor'.scan(/\{@\|(\d+)\|(\w+)\}/)
=> [["42", "user"], ["256", "community"]]

[["42", "user"], ["256", "community"]].map do |mentionable_id, mentionable_type|
  # ...
end
```

2019-01-17 12:42 UTC, Gikls commented on lib/acts_as_mentionable/mentioner_parser.rb
> +        /\{\W\|\d+\|\w+\}/
But you can't gsub the ["256", "community"] array in string. That's why I gsub this template, and get  "{@|123|user}" inclusions to replace it with @ user .

2019-01-17 14:44 UTC, Gikls commented on lib/acts_as_mentionable/mentioner_parser.rb
> +        mentionable_klass.classify.constantize.find mentionable_id
ActiveRecord still requires activesupport. Waiting unltiill it will not.

2019-01-17 15:00 UTC, ux approved these changes

2019-01-17 16:20 UTC, bazay requested changes
Please remove all references to external application i.e. Fuse platform

2019-01-17 16:20 UTC, bazay commented on lib/acts_as_mentionable/active_record_methods.rb
> +      def acts_as_mentioner mention_field = :body
I agree with @ux, `:body` is very specific to monolith application. Please make the mention_field argument a required argument

2019-01-17 16:20 UTC, bazay commented on lib/acts_as_mentionable/active_record_methods.rb
> +          # => :username
Actually gem should not contain any reference to external projects...
Also why are you disabling `rubocop` here - can you not implement it in a way that rubocop is happy with?

2019-01-17 16:20 UTC, bazay commented on lib/acts_as_mentionable/mentioner_parser.rb
> +        /\{\W\|\d+\|\w+\}/
I think `#scan` is also available:
```ruby
template = "Hi, {@|123|user}! Welcome to {@|123|community}"
mention_matching_regex = /\{@\|(\d+)\|(\w+)\}/
template.scan(mention_matching_regex)
# => [["123", "user"], ["123", "community"]]
```

2019-01-17 16:20 UTC, bazay commented on lib/acts_as_mentionable/active_record_methods.rb
> +      def acts_as_mentionable mentionable_delimiter = '@', mentionable_field = :username
I think we can remove mentionable_delimiter for now. Let's just assume that `"@"` is the only supported delimiter, if we want to extend it in the future we can do it in separate PRs. I think the `mentionable_field` argument should remain, however it shouldn't default to `:username` and should be a required argument e.g.:
```ruby
def acts_as_mentionable mentionable_field
  ...
end
```

2019-01-17 18:12 UTC, Gikls commented on lib/acts_as_mentionable/mentioner_parser.rb
> +        /\{\W\|\d+\|\w+\}/
Yeah, but if now I want to replace the [{@|123|user}, {@|123|community}] in original template: With *san* I should scan template again to find {@|123|user} and replace it with "@user123name" . 
In my code I do it in one iteration: gsub with block and while i've found the inclusion, I processing the mentionable and return the correct template for replacement in the end of the block. As result i've got the array of mentionables in mentionables var and as result of gsub block the body like 
"Hi, @123username Welcome to @123community"

2019-01-18 10:48 UTC, bazay approved these changes

2019-01-18 10:49 UTC, merged