feature FINISH-513 add mentions table
Fuseit/acts_as_mentionable pull request #4
Opened 2018-11-27 12:33 UTC by Gikls

https://fuseuniversal.atlassian.net/browse/FINISH-513

2018-11-28 16:17 UTC, bazay approved these changes

2018-11-28 17:43 UTC, ux approved these changes

2018-11-28 17:54 UTC, ux commented on db/migrate/1_acts_as_mentionable_migration.rb
> +    add_index :acts_as_mentionable_mentions, [:mentionee_id, :mentionee_type], name: "mentions_mentionee_idx"
Approved PR, but missed that we are using `mentionable` instead of `mentionee`, so please replace.

2018-11-28 19:22 UTC, bazay requested changes

2018-11-28 19:22 UTC, bazay commented on db/migrate/1_acts_as_mentionable_migration.rb
> +    add_index :acts_as_mentionable_mentions, [:mentionee_id, :mentionee_type], name: "mentions_mentionee_idx"
Ah good find @ux  - this should be changed

2018-11-28 19:22 UTC, bazay commented on db/migrate/1_acts_as_mentionable_migration.rb
> +      t.reference :mentionable, index: false
Are you sure this will create `*_type` column also?
https://guides.rubyonrails.org/active_record_migrations.html#creating-a-standalone-migration

Why not?
```ruby
t.references :mentionable, polymorphic: true, index: { name: 'mentions_mentionable_index' }
t.references :mentioner, polymorphic: true, index: { name: 'mentions_mentioner_index' }
```

2018-11-29 07:52 UTC, Gikls commented on db/migrate/1_acts_as_mentionable_migration.rb
> +      t.reference :mentionable, index: false
@bazay fixed

2018-11-29 15:15 UTC, bazay requested changes

2018-11-29 15:15 UTC, bazay commented on db/migrate/1_acts_as_mentionable_migration.rb
> +      t.reference :mentionable, index: { name: "mentions_mentionee_idx" }
index name should be `mentions_mentionable_idx`, then it's OK

2018-11-30 09:07 UTC, bazay approved these changes
Okay looks good thanks

2018-11-30 09:22 UTC, merged