feature FINISH-514 Create mentionable mixin
Fuseit/acts_as_mentionable pull request #7
Opened 2018-11-28 18:45 UTC by ux

https://fuseuniversal.atlassian.net/browse/FINISH-514

2018-12-04 01:01 UTC, bazay requested changes

2018-12-04 01:01 UTC, bazay commented on spec/internal/models/mentionable.rb
> +class Mentionable < ActiveRecord::Base
I think a better path, and naming is `spec/internal/app/models/mentionable_model.rb` 
Mentionable could get confused with the existing `module` `Mentionable` and I think it's better to avoid that.

2018-12-04 01:01 UTC, bazay commented on spec/internal/models/mentioner.rb
> +class Mentioner < ActiveRecord::Base
Same applies with this file name, and location.

2018-12-04 01:01 UTC, bazay commented on spec/internal/db_schema.rb
> +  create_table :mentionables do |t|
Missed this earlier, but I think it's better to keep as close to Rails folder structure by moving to:
`spec/internal/db/schema.rb`

2018-12-04 01:01 UTC, bazay commented on spec/acts_as_mentionable/mentionable_spec.rb
> +RSpec.describe ActsAsMentionable::Mentionable do
At the moment, I'm not sure if this is intended to test a class, or the mixin. ¯\_(ツ)_/¯
(Although I can hazard a guess that it's the former, I think it's better to be clear and changing below comment to `MentionableModel` should help with this.

2018-12-04 01:01 UTC, bazay commented on spec/acts_as_mentionable/mentionable_spec.rb
> +  let(:mentionable) { Mentionable.create! }
Will `described_class.create!` work here?

2018-12-04 01:01 UTC, bazay commented on spec/acts_as_mentionable/mentionable_spec.rb
> +
remove blank line?

2018-12-04 01:01 UTC, bazay commented on lib/acts_as_mentionable/mentionable.rb
> +        dependent: :delete_all,
Maybe this is okay, but it's worth thinking about what happens when we delete a Mentionable...
1. Let's pretend that we mixin Mentionable on a User.
2. Let's pretend that we mixin Mentioner on a Comment.

I see the following challenges:
1. When we delete a user, we therefore delete_all mentions they have been referenced in (this could be a lot of mentions - and the Mention table could be very large). This therefore may be useful to be performed in a job, so then this gem needs to support job processing but not all projects have such a concerns with scalability. Therefore it's OK for projects inheriting this gem to worry about this concern (e.g. to handle deletion of the Mentionable in their own queueing) however it could be good to leave a comment here warning about such, or to document this in Documentation somewhere. Perhaps Confluence will suffice for now with the remainder of the project documentation so as to keep it all in one place.
2. There's also the issue that the Mentioner i.e. Comment in our main app will no longer support correct interpolation for the missing User. Again I think this can be handled not in the gem and in the separate project, so when we implement in our main application we need to think about how we can resolve this - perhaps show the "safe" mention e.g. '@deleted_user`, etc

2018-12-06 21:11 UTC, ux commented on lib/acts_as_mentionable/mentionable.rb
> +        dependent: :delete_all,
@bazay,

1. I agree that we can handle this in a project, but I would leave this as is for now - `dependent: :delete_all`. Because it's better to keep data integrity, and later we can handle extra cases. And once we start facing any issues with it, or just decide to add a feature not to auto-delete dependent mentions I think that would be a perfect point to make changes.
2. This point is not directly related to `dependent: :delete_all`, but it relates to deleted mentionables. And yeah, I agree that this should not be handled in the gem, or, at least, this should be somehow configurable. I agree that showing "safe" should be fine, but yes, we need to discuss and decide how / when / etc we handle this... I think this can be done on a call or something like that, but not in a scope of this PR.

What do you think?

2018-12-07 11:15 UTC, Gikls approved these changes

2018-12-07 11:45 UTC, bazay approved these changes

2018-12-07 13:53 UTC, merged